name: seyahat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker:
  get:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add your assets here
  assets:
    - assets/seyahat.png
    - assets/smallplane.png
    - assets/mountain.png
    - assets/flower.png
    - assets/user.png
    - assets/guide.png
    - assets/success.png
    - assets/view.png
    #- assets/explore.png

  # You can add more assets like:
  # - assets/image1.png
  # - assets/image2.jpg

  # To add custom fonts, you can uncomment and configure this section:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
